#include "pch.h"
#include "utils/Compiler.h"

#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION

#define TINYGLTF_NOEXCEPTION
#define JSON_NOEXCEPTION

#define TINYGLTF_USE_CPP14

DISABLE_ALL_WARNING
MSVC_DISABLE_WARNING(4996)
MSVC_DISABLE_WARNING(4018)
MSVC_DISABLE_WARNING(4189)
#include "tiny_gltf.h"
