#include "utils/Compiler.h"

DISABLE_ALL_WARNING
#include "volk.h"
#define VMA_IMPLEMENTATION
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
MSVC_DISABLE_WARNING(4100)
MSVC_DISABLE_WARNING(4189)
MSVC_DISABLE_WARNING(4127)
MSVC_DISABLE_WARNING(4324)
MSVC_DISABLE_WARNING(4701)
MSVC_DISABLE_WARNING(4703)
#include "vk_mem_alloc.h"
